// This file will hold helper functions, like generating
// the password and timestamp, to keep our service file clean.
// This fulfills part of FR-GW2 (abstracting complexity).

const { passkey, shortCode } = require("../config/mpesa.config");
const logger = require("../config/logger");

/**
 * @function getTimestamp
 * @description Generates the current timestamp in YYYYMMDDHHMMSS format.
 * @returns {string} The formatted timestamp.
 */
const getTimestamp = () => {
  const now = new Date();
  const year = now.getFullYear().toString().padStart(4, "0");
  const month = (now.getMonth() + 1).toString().padStart(2, "0");
  const day = now.getDate().toString().padStart(2, "0");
  const hours = now.getHours().toString().padStart(2, "0");
  const minutes = now.getMinutes().toString().padStart(2, "0");
  const seconds = now.getSeconds().toString().padStart(2, "0");

  const timestamp = `${year}${month}${day}${hours}${minutes}${seconds}`;
  logger.debug(`Generated M-PESA Timestamp: ${timestamp}`);
  return timestamp;
};

/**
 * @function generatePassword
 * @description Generates the Base64-encoded password required by M-PESA.
 * @param {string} timestamp - The timestamp generated by getTimestamp().
 * @returns {string} The Base64-encoded password.
 */
const generatePassword = (timestamp) => {
  const password = Buffer.from(`${shortCode}${passkey}${timestamp}`).toString(
    "base64"
  );
  logger.debug("Generated M-PESA Password.");
  return password;
};

module.exports = { getTimestamp, generatePassword };
